version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "monthly"
      time: "03:00"
      timezone: "Asia/Tokyo"
    labels:
      - "Type: Dependencies"
    assignees:
      - "RShirohara"
    reviewers:
      - "RShirohara"
