version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "03:00"
      timezone: "Asia/Tokyo"
    labels:
      - "Type: Dependencies"
    assignees:
      - "RShirohara"
    reviewers:
      - "RShirohara"
