version: "3"

services:
  app:
    image: superseriousbusiness/gotosocial:latest
    container_name: gotosocial-app
    user: 1000:1000
    restart: always
    env_file:
      - ./environment/app.env
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: gotosocial-tunnel
    depends_on:
      - app
    restart: always
    command: "tunnel --loglevel debug run"
    env_file:
      - ./environment/tunnel.env
